'use client';
import { useEffect, useRef, useState } from 'react';
import type { AssetSummary } from '@/lib/types';

function numeric(value: unknown, fallback: number): number { const n=Number(value); return Number.isFinite(n)&&n>0?n:fallback; }
export function DepthPreview({asset}:{asset:AssetSummary}){
  const ref=useRef<HTMLCanvasElement|null>(null); const [error,setError]=useState('');
  useEffect(()=>{let cancelled=false;async function load(){if(!asset.url||!ref.current)return;try{const response=await fetch(asset.url);if(!response.ok)throw new Error(`HTTP ${response.status}`);const bytes=new Uint8Array(await response.arrayBuffer());if(cancelled||!ref.current)return;const meta=asset.metadata??{};const width=numeric(meta.width??meta.imageWidth??meta.depthWidth,160);const height=numeric(meta.height??meta.imageHeight??meta.depthHeight,120);const rowStride=numeric(meta.rowStride,asset.kind==='DEPTH_CONFIDENCE'?width:width*2);const pixelStride=numeric(meta.pixelStride,asset.kind==='DEPTH_CONFIDENCE'?1:2);const canvas=ref.current;canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)return;const image=ctx.createImageData(width,height);let min=Infinity,max=-Infinity;const values=new Float32Array(width*height);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const o=y*rowStride+x*pixelStride;let value=0;if(asset.kind==='DEPTH_CONFIDENCE')value=bytes[o]??0;else value=(bytes[o]??0)|((bytes[o+1]??0)<<8);values[y*width+x]=value;if(value>0){min=Math.min(min,value);max=Math.max(max,value);}}if(!Number.isFinite(min)){min=0;max=1;}const range=Math.max(1,max-min);for(let i=0;i<values.length;i++){const value=values[i];const t=value<=0?0:(value-min)/range;const o=i*4;if(asset.kind==='DEPTH_CONFIDENCE'){image.data[o]=35+220*t;image.data[o+1]=55+190*t;image.data[o+2]=80+80*t;}else{image.data[o]=Math.max(0,255*(1.5-Math.abs(4*t-3)));image.data[o+1]=Math.max(0,255*(1.5-Math.abs(4*t-2)));image.data[o+2]=Math.max(0,255*(1.5-Math.abs(4*t-1)));}image.data[o+3]=value<=0?45:255;}ctx.putImageData(image,0,0);}catch(e){setError(e instanceof Error?e.message:'Unable to decode depth');}}void load();return()=>{cancelled=true};},[asset]);
  return <div className="depth-preview">{error?<span>{error}</span>:<canvas ref={ref}/>}<small>{asset.kind.replaceAll('_',' ')}</small></div>;
}
