'use client';
import { useMemo, useState } from 'react';
import type { EvidenceResponse, GeometryProposal, Selection } from '@/lib/types';
import { DepthPreview } from './DepthPreview';
import { PointCloudViewer } from './PointCloudViewer';
import { Icon } from './Icon';

interface Props { evidence: EvidenceResponse|null; selection: Selection; loading:boolean; onDecision:(proposal:GeometryProposal,decision:'ACCEPT'|'REJECT')=>void; onRefresh:()=>void; }
export function EvidenceReview({evidence,selection,loading,onDecision,onRefresh}:Props){const [roomFilter,setRoomFilter]=useState('ALL');const assets=useMemo(()=>{if(!evidence)return[];let list=evidence.assets;const refs:string[]=selection?.kind==='WALL'?[]:[];if(roomFilter!=='ALL')list=list.filter(a=>a.roomId===roomFilter);if(refs.length)list=list.filter(a=>refs.includes(a.id));return list;},[evidence,roomFilter,selection]);const rooms=[...new Set((evidence?.assets??[]).map(a=>a.roomId).filter(Boolean))] as string[];const images=assets.filter(a=>a.kind==='RGB_KEYFRAME'||a.kind==='PHOTO'||a.mimeType.startsWith('image/'));const depth=assets.filter(a=>a.kind==='DEPTH_MAP'||a.kind==='DEPTH_CONFIDENCE');const pointCloud=assets.find(a=>a.kind==='MODEL_EVIDENCE'&&(a.metadata?.type==='FUSED_POINT_CLOUD'||String(a.objectKey??'').endsWith('.ply')));
return <section className="workspace-panel evidence-review"><header><div><span className="eyebrow">Capture evidence</span><h2>Review what supports the model</h2></div><div className="panel-actions"><select value={roomFilter} onChange={e=>setRoomFilter(e.target.value)}><option value="ALL">All rooms</option>{rooms.map(id=><option key={id} value={id}>{id}</option>)}</select><button className="button button-secondary" onClick={onRefresh} disabled={loading}><Icon name="refresh"/>Refresh</button></div></header>{loading&&<div className="panel-loader">Loading signed evidence…</div>}
{evidence&&<><div className="evidence-summary"><article><strong>{evidence.packages.length}</strong><span>Capture packages</span></article><article><strong>{evidence.assets.length}</strong><span>Evidence assets</span></article><article><strong>{evidence.proposals.filter(p=>p.status!=='REJECTED').length}</strong><span>Geometry proposals</span></article><article><strong>{String(evidence.geometryReport?.processorVersion??'—')}</strong><span>Processor</span></article></div>
{pointCloud?.url&&<div className="evidence-block"><h3>Fused point-cloud evidence</h3><PointCloudViewer url={pointCloud.url}/></div>}
<div className="evidence-split"><div><h3>RGB keyframes</h3><div className="evidence-media-grid">{images.slice(0,30).map(asset=><a key={asset.id} className="evidence-media" href={asset.url} target="_blank"><img src={asset.url} alt={asset.kind}/><span>{asset.kind}<small>{asset.roomId??'Structure'}</small></span></a>)}{!images.length&&<p className="empty-note">No browser-previewable RGB images.</p>}</div></div><div><h3>Depth and confidence</h3><div className="depth-grid">{depth.slice(0,12).map(asset=><DepthPreview key={asset.id} asset={asset}/>)}{!depth.length&&<p className="empty-note">No depth assets found.</p>}</div></div></div>
<div className="evidence-block"><h3>Geometry proposals</h3><div className="proposal-table">{evidence.proposals.map(proposal=><article key={proposal.id} className={`proposal-card status-${(proposal.status??'PROPOSED').toLowerCase()}`}><div><strong>{proposal.proposalType.replaceAll('_',' ')}</strong><span>Room {proposal.roomId}</span><small>Confidence {Math.round(proposal.confidence*100)}%{proposal.uncertaintyM?` · ±${proposal.uncertaintyM.toFixed(2)} m`:''}</small></div><pre>{JSON.stringify(proposal.geometry,null,2).slice(0,520)}</pre><div className="proposal-actions"><button onClick={()=>onDecision(proposal,'REJECT')} disabled={proposal.status==='REJECTED'}>Reject</button><button className="accept" onClick={()=>onDecision(proposal,'ACCEPT')} disabled={proposal.status==='ACCEPTED'}>Accept proposal</button></div></article>)}{!evidence.proposals.length&&<p className="empty-note">No automatic proposals are available.</p>}</div></div>
<div className="evidence-block"><h3>Package validation</h3><div className="package-grid">{evidence.packages.map(pkg=><article key={pkg.id}><strong>{pkg.roomId}</strong><span className={pkg.checksumVerified?'text-success':'text-danger'}>{pkg.checksumVerified?'Checksum verified':'Checksum not verified'}</span><small>{pkg.keyframeCount} keyframes · {pkg.status} · schema {pkg.schemaVersion}</small></article>)}</div></div></>}
</section>}
