'use client';
import { useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';
import type { CaptureRegistration, CaptureSnapshot, ProgressCompareResult, ProgressViewerManifest, RegistrationAnchor, SpatialRoomSummary } from '@/lib/types';
import { Pano360Viewer, type PanoViewState } from './Pano360Viewer';

const DEFAULT_VIEW: PanoViewState = { yaw: 0, pitch: 0, fov: 74 };
const defaultAnchors: RegistrationAnchor[] = [0,1,2].map(() => ({ source:[0,0,0], target:[0,0,0] }));
export function ProgressCompareWorkspace({ projectId, snapshots, rooms, initialRegistration, onRegistration }: { projectId:string; snapshots:CaptureSnapshot[]; rooms:SpatialRoomSummary[]; initialRegistration?:CaptureRegistration|null; onRegistration?:(r:CaptureRegistration)=>void }) {
  const [leftId,setLeftId]=useState(snapshots[1]?.id ?? ''); const [rightId,setRightId]=useState(snapshots[0]?.id ?? '');
  const [roomId,setRoomId]=useState(''); const [leftManifest,setLeftManifest]=useState<ProgressViewerManifest|null>(null); const [rightManifest,setRightManifest]=useState<ProgressViewerManifest|null>(null);
  const [view,setView]=useState<PanoViewState>(DEFAULT_VIEW); const [mode,setMode]=useState<'SIDE_BY_SIDE'|'SWIPE'>('SIDE_BY_SIDE'); const [swipe,setSwipe]=useState(50);
  const [compare,setCompare]=useState<ProgressCompareResult|null>(null); const [registration,setRegistration]=useState<CaptureRegistration|null>(initialRegistration ?? null); const [anchors,setAnchors]=useState<RegistrationAnchor[]>(defaultAnchors); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{ if(!leftId||!rightId)return; Promise.all([api.getProgressViewerManifest(leftId),api.getProgressViewerManifest(rightId),api.compareProgressSnapshots(projectId,leftId,rightId,roomId||undefined)]).then(([a,b,c])=>{setLeftManifest(a);setRightManifest(b);setCompare(c);setRegistration(c.registration??null);}).catch(e=>setError(e instanceof Error?e.message:'Compare failed')); },[projectId,leftId,rightId,roomId]);
  const leftRoom=useMemo(()=>leftManifest?.rooms.find(r=>roomId?r.spatialRoomId===roomId:Boolean(r.panoramaUrl)),[leftManifest,roomId]);
  const rightRoom=useMemo(()=>rightManifest?.rooms.find(r=>roomId?r.spatialRoomId===roomId:Boolean(r.panoramaUrl)),[rightManifest,roomId]);
  function updateAnchor(i:number,side:'source'|'target',axis:number,value:string){ setAnchors(cur=>cur.map((a,idx)=>idx===i?{...a,[side]:a[side].map((v,j)=>j===axis?(Number(value)||0):v) as [number,number,number]}:a)); }
  async function register(){ setBusy(true);setError(null);try{const r=await api.assistProgressRegistration(projectId,{sourceSnapshotId:leftId,targetSnapshotId:rightId,anchors,version:'anchor-v1'});setRegistration(r);onRegistration?.(r);}catch(e){setError(e instanceof Error?e.message:'Registration failed');}finally{setBusy(false);} }
  async function decide(d:'VERIFIED'|'REJECTED'){if(!registration)return;const r=await api.decideProgressRegistration(registration.id,d);setRegistration(r);onRegistration?.(r);}
  return <section className="progress-panel-stack"><section className="progress-card"><div className="progress-section-title"><div><p className="eyebrow">Compare v1</p><h2>Reality ↔ Reality</h2></div><div className="compare-mode"><button className={mode==='SIDE_BY_SIDE'?'active':''} onClick={()=>setMode('SIDE_BY_SIDE')}>Side by side</button><button className={mode==='SWIPE'?'active':''} onClick={()=>setMode('SWIPE')}>Swipe</button></div></div>
    <div className="compare-selectors"><label>Earlier<select value={leftId} onChange={e=>setLeftId(e.target.value)}>{snapshots.map(s=><option key={s.id} value={s.id}>{new Date(s.capturedAt).toLocaleString()}</option>)}</select></label><label>Later<select value={rightId} onChange={e=>setRightId(e.target.value)}>{snapshots.map(s=><option key={s.id} value={s.id}>{new Date(s.capturedAt).toLocaleString()}</option>)}</select></label><label>Spatial room<select value={roomId} onChange={e=>setRoomId(e.target.value)}><option value="">First available panorama</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div>
    {error&&<div className="notice notice-error">{error}</div>}
    <div className={`compare-viewer ${mode==='SWIPE'?'swipe':''}`}><div className="compare-pane"><span className="compare-pane-label">Earlier</span>{leftRoom?.panoramaUrl?<Pano360Viewer url={leftRoom.panoramaUrl} viewState={view} onViewStateChange={setView}/>:<div className="compare-empty">No approved panorama for this room.</div>}</div><div className="compare-pane compare-later" style={mode==='SWIPE'?{clipPath:`inset(0 ${100-swipe}% 0 0)`}:undefined}><span className="compare-pane-label">Later</span>{rightRoom?.panoramaUrl?<Pano360Viewer url={rightRoom.panoramaUrl} viewState={view} onViewStateChange={setView}/>:<div className="compare-empty">No approved panorama for this room.</div>}</div></div>
    {mode==='SWIPE'&&<input className="compare-swipe-slider" type="range" min="5" max="95" value={swipe} onChange={e=>setSwipe(Number(e.target.value))}/>}<p className="muted">Camera yaw/pitch/FOV are synchronized. Spatial claims remain blocked until registration is verified.</p>
  </section>
  <section className="progress-card"><div className="progress-section-title"><div><p className="eyebrow">Registration</p><h2>Anchor-assisted alignment</h2></div><strong>{registration?`${Math.round(registration.confidence*100)}% · ${registration.status}`:'Not registered'}</strong></div><p className="muted">Enter the same three physical points in source and target coordinates (metres). The service estimates a rigid transform with scale locked to 1.0.</p><div className="anchor-grid">{anchors.map((a,i)=><div className="anchor-row" key={i}><strong>Anchor {i+1}</strong>{(['source','target'] as const).map(side=><div key={side}><span>{side}</span>{[0,1,2].map(axis=><input key={axis} type="number" step="0.01" value={a[side][axis]} onChange={e=>updateAnchor(i,side,axis,e.target.value)}/>)}</div>)}</div>)}</div><div className="registration-actions"><button className="button button-primary" disabled={busy||!leftId||!rightId||leftId===rightId} onClick={()=>void register()}>{busy?'Registering…':'Estimate registration'}</button>{registration&&<><button className="button button-secondary" onClick={()=>void decide('VERIFIED')}>Verify</button><button className="button button-secondary" onClick={()=>void decide('REJECTED')}>Reject</button></>}</div></section>
  {compare&&<section className="progress-card"><p className="eyebrow">Safe deterministic delta</p><h2>Evidence inventory</h2><p className="muted">{compare.diff.disclaimer}</p><div className="diff-grid">{compare.diff.assetKindDelta.map(row=><article key={row.kind}><strong>{row.kind}</strong><span>{row.source} → {row.target}</span><small>{row.delta===0?'unchanged inventory':`${row.delta>0?'+':''}${row.delta}`}</small></article>)}</div></section>}</section>;
}
