'use client';

import { useEffect, useMemo, useRef } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { TransformControls } from 'three/examples/jsm/controls/TransformControls.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';
import { KTX2Loader } from 'three/examples/jsm/loaders/KTX2Loader.js';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
import { RoundedBoxGeometry } from 'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import { MeshoptDecoder } from 'three/examples/jsm/libs/meshopt_decoder.module.js';
import { modelBounds, normalizeFurniture, wallLength } from '@/lib/model';
import type { CameraMode, DesignModel, FurnitureObject, OpeningModel, Selection, TransformMode, WallModel } from '@/lib/types';

interface Props {
  model: DesignModel;
  selection: Selection;
  cameraMode: CameraMode;
  transformMode: TransformMode;
  showCeiling?: boolean;
  isolateRoomId?: string | null;
  hiddenWallIds?: string[];
  snapshotToken?: number;
  quality?: 'LOW' | 'MEDIUM' | 'HIGH';
  daylight?: number;
  onSelect?: (selection: Selection) => void;
  onChangeObject?: (roomId: string, object: FurnitureObject) => void;
}

type Runtime = {
  scene: THREE.Scene; camera: THREE.PerspectiveCamera; renderer: THREE.WebGLRenderer; controls: OrbitControls;
  transform: TransformControls; transformHelper: THREE.Object3D; box: THREE.BoxHelper | null;
  roomsRoot: THREE.Group; roomGroups: Map<string, THREE.Group>; signatures: Map<string,string>;
  objectMap: Map<string,{ group: THREE.Group; roomId: string; object: FurnitureObject }>;
  selectionMap: Map<string, Selection>; materialCache: Map<string,THREE.Material>; textureCache: Map<string,THREE.Texture>;
  assetCache: Map<string,Promise<THREE.Object3D>>; gltf: GLTFLoader; environmentTarget: THREE.WebGLRenderTarget;
  sun: THREE.DirectionalLight; fill: THREE.PointLight; warm: THREE.PointLight;
};

function colour(name = ''): number { const n=name.toLowerCase(); if(n.includes('sage'))return 0x6f8067;if(n.includes('terracotta'))return 0xb77152;if(n.includes('charcoal'))return 0x34383d;if(n.includes('walnut'))return 0x6b3e25;if(n.includes('oak'))return 0xb48652;if(n.includes('sand'))return 0xc8ae8d;if(n.includes('blue'))return 0x426b83;if(n.includes('metal'))return 0x8c9499;if(n.includes('glass'))return 0xbde7f1;return 0xece8df; }
function stable(value: unknown): string { return JSON.stringify(value); }
function rounded(size:[number,number,number],material:THREE.Material,radius=.04){const geometry=new RoundedBoxGeometry(Math.max(.01,size[0]),Math.max(.01,size[1]),Math.max(.01,size[2]),4,Math.min(radius,Math.min(...size)/3));const mesh=new THREE.Mesh(geometry,material);mesh.castShadow=true;mesh.receiveShadow=true;return mesh;}
function addMesh(parent:THREE.Object3D,geometry:THREE.BufferGeometry,material:THREE.Material,position:[number,number,number]){const mesh=new THREE.Mesh(geometry,material);mesh.position.set(...position);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}

function disposeObject(root:THREE.Object3D, sharedMaterials:Set<THREE.Material>){root.traverse(node=>{if(node instanceof THREE.Mesh){node.geometry.dispose();const mats=Array.isArray(node.material)?node.material:[node.material];mats.forEach(mat=>{if(!sharedMaterials.has(mat)){for(const key of ['map','normalMap','roughnessMap','metalnessMap','aoMap'] as const){const texture=(mat as THREE.MeshStandardMaterial)[key] as THREE.Texture|null|undefined;texture?.dispose();}mat.dispose();}});}});root.removeFromParent();}
function floorGeometry(points:[number,number][]):THREE.ShapeGeometry{const shape=new THREE.Shape();points.forEach(([x,z],i)=>i?shape.lineTo(x,z):shape.moveTo(x,z));shape.closePath();const g=new THREE.ShapeGeometry(shape);g.rotateX(Math.PI/2);return g;}
function wallSegments(wall:WallModel,height:number):Array<{x:number;width:number,bottom:number,height:number,opening?:OpeningModel}>{const length=wallLength(wall);const openings=[...wall.openings].sort((a,b)=>a.offsetM-b.offsetM);const spans:Array<{x:number;width:number,bottom:number,height:number,opening?:OpeningModel}>=[];let cursor=0;for(const o of openings){const start=Math.max(0,Math.min(length,o.offsetM));const end=Math.max(start,Math.min(length,o.offsetM+o.widthM));if(start>cursor+.01)spans.push({x:(cursor+start)/2,width:start-cursor,bottom:0,height});const bottom=o.bottomM??o.sillM??0;if(bottom>.01)spans.push({x:(start+end)/2,width:end-start,bottom:0,height:bottom,opening:o});const top=bottom+o.heightM;if(top<height-.01)spans.push({x:(start+end)/2,width:end-start,bottom:top,height:height-top,opening:o});cursor=end;}if(cursor<length-.01)spans.push({x:(cursor+length)/2,width:length-cursor,bottom:0,height});return spans;}

function material(runtime:Runtime,name='Warm White',kind:'wall'|'floor'|'fabric'|'metal'|'glass'='wall'):THREE.Material{const key=`${kind}:${name}`;const cached=runtime.materialCache.get(key);if(cached)return cached;let mat:THREE.Material;if(kind==='glass')mat=new THREE.MeshPhysicalMaterial({color:colour(name),roughness:.08,metalness:0,transmission:.72,transparent:true,opacity:.48,thickness:.02,side:THREE.DoubleSide});else mat=new THREE.MeshPhysicalMaterial({color:colour(name),roughness:kind==='fabric'?.86:kind==='floor'?.58:kind==='metal'?.28:.78,metalness:kind==='metal'?.72:.01,clearcoat:kind==='floor'?.18:.03,clearcoatRoughness:.5});runtime.materialCache.set(key,mat);return mat;}
function assignSelectable(root:THREE.Object3D,key:string,selection:Selection,runtime:Runtime){root.traverse(node=>{node.userData.selectionKey=key;});runtime.selectionMap.set(key,selection);}

function createFurniture(runtime:Runtime,item:FurnitureObject):THREE.Group{const g=new THREE.Group();g.name=item.name;g.userData.objectId=item.id;const [w,d,h]=item.size;const main=material(runtime,item.material,item.type==='SOFA'||item.type==='CHAIR'||item.type==='BED'?'fabric':item.type==='LAMP'?'metal':'wall');const dark=material(runtime,'Charcoal Fabric','fabric');const light=material(runtime,'Warm White','fabric');
  switch(item.type){case 'SOFA':{const seat=rounded([w,h*.38,d],main,.1);seat.position.y=h*.25;g.add(seat);const back=rounded([w,h*.66,d*.18],main,.07);back.position.set(0,h*.68,-d*.4);back.rotation.x=-.1;g.add(back);[-1,1].forEach(s=>{const arm=rounded([d*.18,h*.54,d],main,.06);arm.position.set(s*w*.47,h*.48,0);g.add(arm)});[-.24,.24].forEach(x=>{const cushion=rounded([w*.42,h*.12,d*.68],light,.055);cushion.position.set(x*w,h*.5,.02);g.add(cushion)});break;}case 'CHAIR':{const seat=rounded([w*.9,h*.15,d*.86],main,.06);seat.position.y=h*.45;g.add(seat);const back=rounded([w*.9,h*.58,d*.16],main,.06);back.position.set(0,h*.7,-d*.36);back.rotation.x=-.12;g.add(back);break;}case 'BED':{const base=rounded([w,h*.3,d],dark,.07);base.position.y=h*.18;g.add(base);const mattress=rounded([w*.96,h*.28,d*.94],main,.09);mattress.position.y=h*.43;g.add(mattress);const head=rounded([w,h*1.15,d*.13],main,.06);head.position.set(0,h*.62,-d*.46);g.add(head);[-.25,.25].forEach(x=>{const pillow=rounded([w*.38,h*.15,d*.28],light,.06);pillow.position.set(x*w,h*.72,-d*.24);g.add(pillow)});break;}case 'TABLE':{const top=rounded([w,h*.12,d],main,.05);top.position.y=h*.9;g.add(top);[-1,1].forEach(x=>[-1,1].forEach(z=>addMesh(g,new THREE.CylinderGeometry(.035,.045,h*.86,12),dark,[x*w*.4,h*.43,z*d*.38])));break;}case 'PLANT':{addMesh(g,new THREE.CylinderGeometry(w*.25,w*.34,h*.28,24),material(runtime,'Terracotta Accent'),[0,h*.14,0]);for(let i=0;i<9;i++){const leaf=addMesh(g,new THREE.SphereGeometry(w*.22,16,10),material(runtime,'Sage Accent'),[Math.sin(i*2.4)*w*.22,h*.36+(i%3)*h*.2,Math.cos(i*2.4)*d*.22]);leaf.scale.set(.55,1.5,.35);}break;}case 'LAMP':{addMesh(g,new THREE.CylinderGeometry(.025,.035,h*.78,12),material(runtime,'Brushed Metal','metal'),[0,h*.39,0]);addMesh(g,new THREE.ConeGeometry(w*.32,h*.28,32,1,true),new THREE.MeshPhysicalMaterial({color:0xf3dfb8,roughness:.8,side:THREE.DoubleSide,emissive:0xffd28a,emissiveIntensity:.18}),[0,h*.86,0]);break;}case 'RUG':{const rug=rounded([w,h,d],main,.012);rug.position.y=h/2+.006;g.add(rug);break;}default:{const body=rounded([w,h,d],main,.05);body.position.y=h/2;g.add(body);}}
  g.position.set(item.position[0],item.elevationM??0,item.position[1]);g.rotation.y=item.rotationY;g.visible=item.visible!==false;g.userData.roomId='';g.userData.object=item;return g;}

async function loadAsset(runtime:Runtime,url:string):Promise<THREE.Object3D>{let cached=runtime.assetCache.get(url);if(!cached){cached=new Promise((resolve,reject)=>runtime.gltf.load(url,g=>resolve(g.scene),undefined,reject));runtime.assetCache.set(url,cached);}const source=await cached;return source.clone(true);}

function buildRoom(runtime:Runtime,room:DesignModel['rooms'][number],showCeiling:boolean,hiddenWallIds:Set<string>):THREE.Group{const group=new THREE.Group();group.name=room.name;assignSelectable(group,`room:${room.id}`,{kind:'ROOM',roomId:room.id},runtime);const floor=new THREE.Mesh(floorGeometry(room.floorPolygon),material(runtime,'Oak Wood','floor'));floor.receiveShadow=true;floor.userData.selectionKey=`room:${room.id}`;group.add(floor);
  room.walls.forEach(wall=>{const len=wallLength(wall)||.01;const angle=-Math.atan2(wall.end[1]-wall.start[1],wall.end[0]-wall.start[0]);const wallGroup=new THREE.Group();wallGroup.position.set(wall.start[0],0,wall.start[1]);wallGroup.rotation.y=angle;wallGroup.visible=!hiddenWallIds.has(wall.id);const wallKey=`wall:${room.id}:${wall.id}`;assignSelectable(wallGroup,wallKey,{kind:'WALL',roomId:room.id,wallId:wall.id},runtime);wallSegments(wall,room.heightM).forEach(segment=>{const mesh=rounded([segment.width,segment.height,wall.thicknessM],material(runtime,wall.material),.015);mesh.position.set(segment.x,segment.bottom+segment.height/2,0);mesh.userData.selectionKey=wallKey;wallGroup.add(mesh);});
    wall.openings.forEach(opening=>{const openingKey=`opening:${room.id}:${wall.id}:${opening.id}`;const frameMat=material(runtime,'Walnut Wood');const start=opening.offsetM;const bottom=opening.bottomM??opening.sillM??0;const frame=new THREE.Group();frame.position.set(start+opening.widthM/2,bottom,0);assignSelectable(frame,openingKey,{kind:'OPENING',roomId:room.id,wallId:wall.id,openingId:opening.id},runtime);const side=.045;[-1,1].forEach(s=>{const m=rounded([side,opening.heightM,.08],frameMat,.01);m.position.set(s*opening.widthM/2,opening.heightM/2,0);frame.add(m)});const top=rounded([opening.widthM+side*2,side,.08],frameMat,.01);top.position.set(0,opening.heightM,0);frame.add(top);if(opening.type==='WINDOW'){const glass=rounded([opening.widthM,opening.heightM,.018],material(runtime,'Clear Glass','glass'),.005);glass.position.set(0,opening.heightM/2,.006);frame.add(glass);}if(opening.type==='DOOR'){const door=rounded([opening.widthM*.96,opening.heightM*.98,.035],material(runtime,'Walnut Wood'),.015);door.position.set(opening.swing?.includes('RIGHT')?-opening.widthM*.48:opening.widthM*.48,opening.heightM/2,.025);door.rotation.y=opening.swing?.includes('OUT')?-.35:.35;frame.add(door);}wallGroup.add(frame);});group.add(wallGroup);
    const skirt=rounded([len,.08,.055],material(runtime,'Cool White'),.012);skirt.position.set((wall.start[0]+wall.end[0])/2,.06,(wall.start[1]+wall.end[1])/2);skirt.rotation.y=angle;group.add(skirt);
  });
  if(showCeiling){const ceiling=new THREE.Mesh(floorGeometry(room.floorPolygon),new THREE.MeshStandardMaterial({color:0xf5f2eb,roughness:1,side:THREE.DoubleSide}));ceiling.position.y=room.heightM;group.add(ceiling);}
  room.objects.forEach(raw=>{const item=normalizeFurniture(raw);if(!item)return;const objectGroup=createFurniture(runtime,item);objectGroup.userData.roomId=room.id;const key=`object:${room.id}:${item.id}`;assignSelectable(objectGroup,key,{kind:'OBJECT',roomId:room.id,objectId:item.id},runtime);group.add(objectGroup);runtime.objectMap.set(item.id,{group:objectGroup,roomId:room.id,object:item});if(item.assetUrl){void loadAsset(runtime,item.assetUrl).then(asset=>{if(!objectGroup.parent)return;asset.traverse(node=>{if(node instanceof THREE.Mesh){node.castShadow=true;node.receiveShadow=true;}});const box=new THREE.Box3().setFromObject(asset);const size=box.getSize(new THREE.Vector3());const scale=Math.min(item.size[0]/Math.max(size.x,.001),item.size[2]/Math.max(size.z,.001),item.size[1]/Math.max(size.y,.001));asset.scale.setScalar(scale);const fitted=new THREE.Box3().setFromObject(asset);const center=fitted.getCenter(new THREE.Vector3());asset.position.set(-center.x,-fitted.min.y,-center.z);objectGroup.children.forEach(c=>c.visible=false);objectGroup.add(asset);}).catch(()=>{});}}
  );return group;}

export function ScenePreview({model,selection,cameraMode,transformMode,showCeiling=false,isolateRoomId=null,hiddenWallIds=[],snapshotToken=0,quality='HIGH',daylight=1,onSelect,onChangeObject}:Props){const hostRef=useRef<HTMLDivElement|null>(null);const runtimeRef=useRef<Runtime|null>(null);const selectRef=useRef(onSelect);const changeRef=useRef(onChangeObject);selectRef.current=onSelect;changeRef.current=onChangeObject;const hiddenSet=useMemo(()=>new Set(hiddenWallIds),[hiddenWallIds]);
  useEffect(()=>{const host=hostRef.current;if(!host)return;const scene=new THREE.Scene();scene.background=new THREE.Color(0x101820);scene.fog=new THREE.Fog(0x101820,28,75);const camera=new THREE.PerspectiveCamera(44,1,.04,300);const renderer=new THREE.WebGLRenderer({antialias:quality!=='LOW',preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='HIGH'?2:1.35));renderer.shadowMap.enabled=quality!=='LOW';renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.06;host.appendChild(renderer.domElement);const pmrem=new THREE.PMREMGenerator(renderer);const environment=new RoomEnvironment();const environmentTarget=pmrem.fromScene(environment,.04);scene.environment=environmentTarget.texture;const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=.7;controls.maxDistance=80;controls.maxPolarAngle=Math.PI*.495;const roomsRoot=new THREE.Group();scene.add(roomsRoot);const transform=new TransformControls(camera,renderer.domElement);const transformHelper=transform.getHelper();scene.add(transformHelper);const sun=new THREE.DirectionalLight(0xfff1d5,4.3);sun.position.set(-5,11,7);sun.castShadow=true;sun.shadow.mapSize.set(quality==='HIGH'?2048:1024,quality==='HIGH'?2048:1024);sun.shadow.camera.left=-25;sun.shadow.camera.right=25;sun.shadow.camera.top=25;sun.shadow.camera.bottom=-25;scene.add(new THREE.HemisphereLight(0xdff9ff,0x10151c,2.05),sun);const fill=new THREE.PointLight(0x86b9ff,5.2,28,2);const warm=new THREE.PointLight(0xffc982,4.3,24,2);scene.add(fill,warm);const grid=new THREE.GridHelper(60,80,0x547588,0x26353f);grid.position.y=-.018;(grid.material as THREE.Material).transparent=true;(grid.material as THREE.Material).opacity=.14;scene.add(grid);
    const gltf=new GLTFLoader();gltf.setMeshoptDecoder(MeshoptDecoder);const dracoPath=process.env.NEXT_PUBLIC_DRACO_DECODER_PATH;if(dracoPath){const draco=new DRACOLoader();draco.setDecoderPath(dracoPath);gltf.setDRACOLoader(draco);}const ktxPath=process.env.NEXT_PUBLIC_KTX2_TRANSCODER_PATH;if(ktxPath){const ktx=new KTX2Loader();ktx.setTranscoderPath(ktxPath);ktx.detectSupport(renderer);gltf.setKTX2Loader(ktx);}
    const runtime:Runtime={scene,camera,renderer,controls,transform,transformHelper,box:null,roomsRoot,roomGroups:new Map(),signatures:new Map(),objectMap:new Map(),selectionMap:new Map(),materialCache:new Map(),textureCache:new Map(),assetCache:new Map(),gltf,environmentTarget,sun,fill,warm};runtimeRef.current=runtime;
    transform.addEventListener('dragging-changed',(event)=>{controls.enabled=!event.value;});transform.addEventListener('objectChange',()=>runtime.box?.update());transform.addEventListener('mouseUp',()=>{const object=transform.object;if(!object)return;const objectId=object.userData.objectId as string|undefined;const found=objectId?runtime.objectMap.get(objectId):undefined;if(!found||!changeRef.current)return;const scale=object.scale;changeRef.current(found.roomId,{...found.object,position:[object.position.x,object.position.z],elevationM:object.position.y,rotationY:object.rotation.y,size:[found.object.size[0]*scale.x,found.object.size[1]*scale.z,found.object.size[2]*scale.y]});object.scale.set(1,1,1);});
    const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();const click=(event:PointerEvent)=>{if((event.target as HTMLElement).closest('.scene-overlay-control'))return;const rect=renderer.domElement.getBoundingClientRect();pointer.x=((event.clientX-rect.left)/rect.width)*2-1;pointer.y=-((event.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(roomsRoot.children,true);for(const hit of hits){let node:THREE.Object3D|null=hit.object;while(node&&!node.userData.selectionKey)node=node.parent;const key=node?.userData.selectionKey as string|undefined;if(key){selectRef.current?.(runtime.selectionMap.get(key)??null);return;}}selectRef.current?.(null);};renderer.domElement.addEventListener('pointerdown',click);
    const resize=()=>{const width=Math.max(1,host.clientWidth),height=Math.max(1,host.clientHeight);renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(host);resize();let frame=0;const animate=()=>{controls.update();runtime.box?.update();renderer.render(scene,camera);frame=requestAnimationFrame(animate)};animate();
    return()=>{cancelAnimationFrame(frame);observer.disconnect();renderer.domElement.removeEventListener('pointerdown',click);controls.dispose();transform.dispose();const shared=new Set(runtime.materialCache.values());[...runtime.roomGroups.values()].forEach(g=>disposeObject(g,shared));runtime.materialCache.forEach(m=>m.dispose());runtime.textureCache.forEach(t=>t.dispose());environmentTarget.dispose();pmrem.dispose();renderer.dispose();renderer.domElement.remove();runtimeRef.current=null;};
  },[quality]);

  useEffect(()=>{const runtime=runtimeRef.current;if(!runtime)return;const clearRoomMaps=(roomId:string)=>{for(const [id,value] of runtime.objectMap)if(value.roomId===roomId)runtime.objectMap.delete(id);for(const [key,value] of runtime.selectionMap)if(value?.roomId===roomId)runtime.selectionMap.delete(key);};const shared=new Set(runtime.materialCache.values());const live=new Set(model.rooms.map(r=>r.id));for(const [id,group] of runtime.roomGroups){if(!live.has(id)){clearRoomMaps(id);disposeObject(group,shared);runtime.roomGroups.delete(id);runtime.signatures.delete(id);}}
    model.rooms.forEach(room=>{const signature=stable({room,showCeiling,hidden:[...hiddenSet].filter(id=>room.walls.some(w=>w.id===id))});if(runtime.signatures.get(room.id)===signature){const existing=runtime.roomGroups.get(room.id);if(existing)existing.visible=!isolateRoomId||isolateRoomId===room.id;return;}const old=runtime.roomGroups.get(room.id);if(old){clearRoomMaps(room.id);disposeObject(old,shared);}const group=buildRoom(runtime,room,showCeiling,hiddenSet);group.visible=!isolateRoomId||isolateRoomId===room.id;runtime.roomsRoot.add(group);runtime.roomGroups.set(room.id,group);runtime.signatures.set(room.id,signature);});
  },[model,showCeiling,isolateRoomId,hiddenSet]);

  useEffect(()=>{const runtime=runtimeRef.current;if(!runtime)return;runtime.transform.detach();if(runtime.box){runtime.box.removeFromParent();runtime.box.geometry.dispose();(runtime.box.material as THREE.Material).dispose();runtime.box=null;}if(selection?.kind==='OBJECT'){const found=runtime.objectMap.get(selection.objectId);if(found&&!found.object.locked){runtime.transform.attach(found.group);runtime.transform.setMode(transformMode);runtime.transform.setSpace('local');runtime.transform.setSize(.72);}if(found){runtime.box=new THREE.BoxHelper(found.group,new THREE.Color(0x6effcf));runtime.scene.add(runtime.box);}}else if(selection){let key='';if(selection.kind==='ROOM')key=`room:${selection.roomId}`;if(selection.kind==='WALL')key=`wall:${selection.roomId}:${selection.wallId}`;if(selection.kind==='OPENING')key=`opening:${selection.roomId}:${selection.wallId}:${selection.openingId}`;if(key){let target:THREE.Object3D|undefined;runtime.scene.traverse(node=>{if(!target&&node.userData.selectionKey===key)target=node;});if(target){runtime.box=new THREE.BoxHelper(target,new THREE.Color(0xffaa63));runtime.scene.add(runtime.box);}}}},[selection,transformMode,model]);

  useEffect(()=>{const runtime=runtimeRef.current;if(!runtime)return;const bounds=modelBounds(model);const cx=(bounds.minX+bounds.maxX)/2,cz=(bounds.minY+bounds.maxY)/2,span=Math.max(bounds.maxX-bounds.minX,bounds.maxY-bounds.minY,4);runtime.controls.target.set(cx,1.1,cz);runtime.controls.enableRotate=true;if(cameraMode==='TOP'){runtime.camera.position.set(cx,Math.max(9,span*1.8),cz+.01);runtime.controls.enableRotate=false;}else if(cameraMode==='FRONT'){runtime.camera.position.set(cx,1.6,cz+span*1.9);runtime.controls.target.set(cx,1.3,cz);}else if(cameraMode==='SIDE'){runtime.camera.position.set(cx+span*1.9,1.6,cz);runtime.controls.target.set(cx,1.3,cz);}else if(cameraMode==='WALKTHROUGH'){runtime.camera.position.set(cx,1.55,cz+span*.3);runtime.controls.target.set(cx,1.35,cz-span*.55);runtime.controls.maxPolarAngle=Math.PI*.62;}else{runtime.camera.position.set(cx+span*1.15,span*.85+2,cz+span*1.25);runtime.controls.maxPolarAngle=Math.PI*.495;}runtime.fill.position.set(cx+span*.35,2.2,cz-span*.3);runtime.warm.position.set(cx-span*.3,1.7,cz+span*.3);runtime.sun.intensity=4.3*daylight;runtime.controls.update();},[cameraMode,model,daylight]);

  useEffect(()=>{if(!snapshotToken)return;const runtime=runtimeRef.current;if(!runtime)return;requestAnimationFrame(()=>{runtime.renderer.render(runtime.scene,runtime.camera);const a=document.createElement('a');a.download=`propertytour360-view-${snapshotToken}.png`;a.href=runtime.renderer.domElement.toDataURL('image/png');a.click();});},[snapshotToken]);
  return <div className="scene-preview scene-preview-v3" ref={hostRef}><div className="scene-tip">Semantic selection · PBR scene · Cached GLB assets · Transform gizmo</div></div>;
}
